# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 02:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmarks',
            old_name='bookmarks_title',
            new_name='name',
        ),
    ]
