# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_auto_20170811_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
