# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0003_auto_20170724_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarks',
            name='bookmarks_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='bookmarks_links',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='bookmarks_title',
            field=models.CharField(max_length=255),
        ),
    ]
