# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_auto_20170723_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsboard',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='list_description',
            field=models.TextField(),
        ),
    ]
